Fix pinot schema mismatch
Summary:
**What is wrong:**
When there are 0 rows matched/returned for a segment, the column types in the Pinot schema are all STRING regardless of the original type, resulting in type mismatch.
```
Failed to write column vehicleViewId. pinotColumnType STRING, javaType long
```

Happy dataTable:
- dataSchema: {"vehicleViewId":"**LONG**", "vehicleViewName":"STRING"}
- numberOfRows: 100
- encodedData: ^(&%^(FUTFI

Bad dataTable:
- dataSchema: {"vehicleViewId":"**STRING**", "vehicleViewName":"STRING"}
- numberOfRows: 0
- encodedData: empty

Note that the schema is not the originally correct schema, though we can and should infer that the latter table is empty and skip directly.

**What is the fix:**

Add a filter on the number of rows returned, and skip any processing on empty tables, so it will not throw exceptions on type mismatch.

Wrong type issues inside Pinot should be fixed separately (might not be high priority since there are other signals to avoid this).

**Why it was not detected earlier:**
 - Before the refactor, we did not throw exceptions on type mismatch, so such cases would fail silently, which is also fine sine the dataTable is empty anyways
- After the refactor, we did not discover this issue with the benchmarked queries. We should expand the query samples (pin-pointed queries like `WHERE trip_uuid = 'XXX'` should be able to catch this)

Test Plan:
Tested in presto-dev-worker

One thing to mention is that I get errors with the current presto-udeploy master when deploying to dev workers
```
2018-10-26T21:03:33.254Z        ERROR   main    com.facebook.presto.server.PrestoServer Unable to create injector, see the following errors:

1) Configuration property 'distributed-joins-enabled' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:234)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'distributed-joins-enabled' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:234)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:241)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:115)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
```

After removing `distributed-joins-enabled=true` ([[ https://code.uberinternal.com/rDAPREBGe3477b32c53b1287e0cb2a0ae58775f75c83b548 | diff link ]]), the dev hosts started successfully.

Is this the expected behavior? @luoz

Reviewers: #streaming_pinot, luoz

Reviewed By: luoz

Subscribers: jenkins

Differential Revision: https://code.uberinternal.com/D2206517